### PR TITLE
Typo fixes / corrections / improvements

### PR DESCRIPTION
**Pull request by gipert**
Work in progress...

### CODE REVIEW

**Comment by mmatteo** [comment]
@ggmarshall, can you please have a look at the changes related to the code (e.g. the import of lhf5) and merge this pull request if you are happy with it?

**Comment by mmatteo** [comment]
@ggmarshall, also, can we remove the two scripts in tier-data/plotting? I think they are different from what we have in the readme, and they are not particularly useful

**Comment by gipert** [comment]
For the record, I just reviewed the tier-data and run-production tutorials. I'll open a separate PR for the other two soon.

**Comment by ggmarshall** [comment]
All looks good to me

**Comment by gipert** [comment]
Probably yesterday I was still using the master branch by mistake, I realize now that the waveform plotting snippet does not work with the `dev` branch. Looks like `lh5.Store.read_object` cannot read tables anymore, only columns.

**Comment by ggmarshall** [comment]
We can just load the waveform directly
tb_data, n_rows = sto.read_object('raw/waveform/values', f_raw, n_rows=30)
wfs_all = tb_data.nda

**Comment by gipert** [comment]
Yep, that fixes it. I am just wondering if this is a bug or it's intended

**Pull request merged**
